# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ec6bb5b80e11111ba38ef408a3cb4462d8b110cb8da3622f6a75fdd141bc8130a9663415050ce38e7ad1124364e66cbcc6358beb5d9788095caf78b14f031d

test:
  secret_key_base: a335cf4ab5a10961c7652e26d2628a4b3bd493d213feacc92f143e7b4db1c3cf0eaa19a1975df9ba2347c7d3597ef992b4ca222f05369a5f3f50f7b1d927e507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
